---
- hosts: localhost
  become: yes


  pre_tasks:
    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Ensure MariaDB is running and enabled
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Wait for MariaDB to be available
      wait_for:
        port: 3306
        host: "127.0.0.1"
        state: started
        delay: 2
        timeout: 30

    - name: Ensure keystone user exists
      ansible.builtin.user:
        name: keystone
        system: yes
        shell: /usr/sbin/nologin


    - name: Ensure Keystone log directory exists and is owned by keystone
      file:
        path: /var/log/keystone
        state: directory
        owner: keystone
        group: keystone
        mode: "0750"

  roles:
    - keystone
