- name: Launch test VM
  openstack.cloud.server:
    state: present
    name: ansible-test
    image: cirros
    flavor: small
    network: demo-net
    timeout: 600

- name: Delete test VM
  openstack.cloud.server:
    state: absent
    name: ansible-test 