---
- name: Install Glance packages
  apt:
    name: glance
    state: present

- name: Configure Glance
  template:
    src: glance-api.conf.j2
    dest: /etc/glance/glance-api.conf
    owner: root
    group: glance
    mode: 0640

- name: Initialize Glance DB
  command: "glance-manage db_sync"
  args:
    creates: /var/lib/glance/glance.sqlite