# Project information
site_name: Adorsys OpenStack
site_description: "OpenStack project backed by adorsys"
site_url: "https://openstack.github.io/adorsys-gis"

# Theme settings
theme:
  name: material
  locale: en
  highlightjs: true
  palette:
    scheme: slate
    primary: purple

# Navbar settings (site structure)
nav:
  - Home: index.md
  - Documentation:
      - Ansible: ansible_docs.md
      - NetPlan: netplan_doc.md
      - NTP: ntp_docs.md
      - VLAN: VLAN.md
  - NetBird:
      - Troubleshooting: netbird/netbird_troubleshooting.md
      - Access Review: netbird/netbird_access_review.md
  - Tutorials:
      - Ansible Tutorial: tutorials/ansible_tuto.md
      - Boot Documentation: tutorials/boot_docs.md
      - Minimal KVM Setup: tutorials/minimal_kvm_setup.md
      - NTP Setup Tutorial: tutorials/ntp_setup_tuto.md
      - Setup vSwitch: tutorials/setupvswitch.md
      - Setting Up Monitoring Netbrid: tutorials/netbird_wazuh_integration.md
# Extra settings
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

repo_name: OpenStack
repo_url: https://github.com/adorsys-gis/openstack
edit_uri: edit/main/docs/
