# Project information
site_name: Adorsys OpenStack
site_description: "OpenStack project backed by adorsys"
site_url: "https://openstack.github.io/adorsys-gis"

# Theme settings
theme:
  name: material
  locale: en
  highlightjs: true
  palette:
    scheme: slate
    primary: purple

# Navbar settings (site structure)
nav:
  - Home: README.md
  - Documentation:
    - Ansible: docs/ansible_docs.md
    - NetPlan: docs/netplan_doc.md
    - NTP: docs/ntp_docs.md
    - VLAN: docs/VLAN.md
  - NetBird:
    - Troubleshooting: docs/netbird/netbird_troubleshooting.md
    - Access Review: docs/netbird/netbird_access_review.md
  - Tutorials:
    - Ansible Tutorial: docs/tutorials/ansible_tuto.md
    - Boot Documentation: docs/tutorials/boot_docs.md
    - Minimal KVM Setup: docs/tutorials/minimal_kvm_setup.md
    - NTP Setup Tutorial: docs/tutorials/ntp_setup_tuto.md
    - Setup vSwitch: docs/tutorials/setupvswitch.md

# Extra settings
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

repo_name: OpenStack
repo_url: https://github.com/adorsys-gis/openstack
edit_uri: edit/main/docs/
