version: '3.7'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: '{{ mysql_root_pass }}'
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - openstack_network

  keystone:
    build:
      context: .
      dockerfile: Dockerfile.keystone
    container_name: keystone
    depends_on:
      - mariadb
    environment:
      - MYSQL_ROOT_PASSWORD={{ mysql_root_pass }}
      - KEYSTONE_DB_PASS={{ keystone_db_pass }}
      - KEYSTONE_ADMIN_PASS={{ keystone_admin_pass }}
      - CONTROLLER_HOST=controller
      - KEYSTONE_PORT=5000
    volumes:
      - ./init-scripts:/init-scripts
    networks:
      - openstack_network
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 5s
      timeout: 10s
      retries: 5

  glance:
    build:
      context: .
      dockerfile: Dockerfile.glance
    container_name: glance
    depends_on:
      - keystone
    environment:
      - MYSQL_ROOT_PASSWORD={{ mysql_root_pass }}
      - GLANCE_DB_PASS={{ glance_db_pass }}
      - GLANCE_USER_PASS={{ glance_user_pass }}
      - KEYSTONE_ADMIN_PASS={{ keystone_admin_pass }}
      - CONTROLLER_HOST=controller
      - KEYSTONE_PORT=5000
    volumes:
      - ./init-scripts:/init-scripts
      - glance_data:/var/lib/glance
    networks:
      - openstack_network
    ports:
      - "9292:9292"

volumes:
  mariadb_data:
  glance_data:

networks:
  openstack_network:
