- name: Restart neutron-server
  service:
    name: neutron-server
    state: restarted
    enabled: yes
  when: inventory_hostname in groups["controllers"]

- name: Restart neutron-linuxbridge-agent
  service:
    name: neutron-linuxbridge-agent
    state: restarted
    enabled: yes

- name: Restart neutron-l3-agent
  service:
    name: neutron-l3-agent
    state: restarted
    enabled: yes
  when: inventory_hostname in groups["controllers"]

- name: Restart neutron-dhcp-agent
  service:
    name: neutron-dhcp-agent
    state: restarted
    enabled: yes
  when: inventory_hostname in groups["controllers"]

- name: Restart neutron-metadata-agent
  service:
    name: neutron-metadata-agent
    state: restarted
    enabled: yes
  when: inventory_hostname in groups["controllers"]
