---
- name: Install nova-compute
  apt:
    name: nova-compute
    state: present

- name: Configure nova-compute
  template:
    src: nova-compute.conf.j2
    dest: /etc/nova/nova.conf
    owner: root
    group: nova
    mode: 0640
  notify: Restart nova-compute

- name: Ensure nova-compute is started and enabled
  service:
    name: nova-compute
    state: started
    enabled: yes

