---
- name: Ensure /opt/stack/devstack is not already cloned
  stat:
    path: "{{ devstack_dir }}/.git"
  register: devstack_repo

- name: Clone DevStack repository
  git:
    repo: "{{ devstack_repo }}"
    dest: "{{ devstack_dir}}"
    version: "{{ openstack_branch }}"
    force: no
  become: yes
  become_user: "{{ stack_user }}"
  when: not devstack_repo.stat.exists
