---
- name: Install Nova packages
  apt:
    name:
      - nova-api
      - nova-conductor
      - nova-novncproxy
      - nova-scheduler
    state: present

- name: Configure Nova
  template:
    src: nova.conf.j2
    dest: /etc/nova/nova.conf
    owner: root
    group: nova
    mode: 0640
  notify: Restart nova services

- name: Sync Nova API DB
  command: nova-manage api_db sync
  args:
    creates: /var/lib/nova/api_db_synced

- name: Map cell0
  command: nova-manage cell_v2 map_cell0
  args:
    creates: /var/lib/nova/cell0_mapped

- name: Create cell1
  command: nova-manage cell_v2 create_cell --name=cell1
  args:
    creates: /var/lib/nova/cell1_created

- name: Sync Nova DB
  command: nova-manage db sync
  args:
    creates: /var/lib/nova/db_synced