---
- name: Install Nova controller packages
  apt:
    name:
      - nova-api
      - nova-conductor
      - nova-novncproxy
      - nova-scheduler
    state: present
  when: "'controllers' in group_names"

- name: Configure Nova
  template:
    src: nova.conf.j2
    dest: /etc/nova/nova.conf
    owner: root
    group: nova
    mode: 0640
  notify: Restart nova services


- name: Sync Nova API DB
  command: nova-manage api_db sync
  args:
    creates: /var/lib/nova/api_db_synced
  when: "'controllers' in group_names"
  
- name: Map cell0
  command: nova-manage cell_v2 map_cell0
  args:
    creates: /var/lib/nova/cell0_mapped
  when: "'controllers' in group_names"

- name: Check if cell1 already exists
  command: nova-manage cell_v2 list_cells
  register: cell_list
  changed_when: false
  failed_when: false

- name: Create cell1 if it does not exist
  command: nova-manage cell_v2 create_cell --name=cell1
  args:
    creates: /var/lib/nova/cell1_created
  when: cell_list.stdout is not search('cell1')


- name: Sync Nova DB
  command: nova-manage db sync
  args:
    creates: /var/lib/nova/db_synced
  when: "'controllers' in group_names"