---
galaxy_info:
  author: onelrian
  description: Launch and verify a test VM for Nova service integration testing.
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  categories:
    - cloud
    - openstack
dependencies: []
