---
# Seting up and installing required packages on the controller node.
- name: Include common tasks
  include_role:
    name: common
    tasks_from: main

- name: Install controller packages
  apt:
    name: "{{ neutron_ubuntu_packages if ansible_os_family == 'Debian' else neutron_centos_packages }}"
    state: present

- name: Create Neutron database
  command: >
    mysql -h {{ neutron_db_host }} 
    -u root 
    -p {{ mysql_root_password }} 
    -e "CREATE DATABASE IF NOT EXISTS {{ neutron_db_name }} 
        CHARACTER SET utf8 
        COLLATE utf8_general_ci"
  args:
    creates: "/var/lib/mysql/{{ neutron_db_name }}"

# communicating/interacting with the mariadb database

- name: Create Neutron database user
  community.mysql.mysql_user:
    name: "{{ neutron_db_user }}"
    password: "{{ neutron_db_password }}"
    host: "%"
    priv: "{{ neutron_db_name }}.*:ALL"
    state: present

- name: Configure ML2 plugin
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    owner: root
    group: neutron
    mode: "0640"
  notify: Restart neutron-server

- name: Configure L3 agent
  template:
    src: l3_agent.ini.j2
    dest: /etc/neutron/l3_agent.ini
    owner: root
    group: neutron
    mode: "0640"
  notify: Restart neutron-l3-agent

- name: Configure DHCP agent
  template:
    src: dhcp_agent.ini.j2
    dest: /etc/neutron/dhcp_agent.ini
    owner: root
    group: neutron
    mode: "0640"
  notify: Restart neutron-dhcp-agent

- name: Configure metadata agent
  template:
    src: metadata_agent.ini.j2
    dest: /etc/neutron/metadata_agent.ini
    owner: root
    group: neutron
    mode: "0640"
  notify: Restart neutron-metadata-agent

- name: Populate Neutron database
  command: >
    neutron-db-manage --config-file /etc/neutron/neutron.conf
    --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  become: yes

# this one is using openstack commands from ansible galaxy to create a neutron service in keystone.

- name: Register Neutron service in Keystone
  openstack.cloud.catalog_service:
    cloud: "{{ lookup('env', 'OS_CLOUD') }}"
    name: network
    service_type: network
    description: "OpenStack Networking Service"
    state: present

- name: Create public endpoint
  openstack.cloud.endpoint:
    cloud: "{{ lookup('env', 'OS_CLOUD') }}"
    service: network
    interface: public
    url: "http://{{ ansible_fqdn }}:9696"
    region: RegionOne
    state: present

- name: Create internal endpoint
  openstack.cloud.endpoint:
    cloud: "{{ lookup('env', 'OS_CLOUD') }}"
    service: network
    interface: internal
    url: "http://{{ ansible_fqdn }}:9696"
    region: RegionOne
    state: present

- name: Create admin endpoint
  openstack.cloud.endpoint:
    cloud: "{{ lookup('env', 'OS_CLOUD') }}"
    service: network
    interface: admin
    url: "http://{{ ansible_fqdn }}:9696"
    region: RegionOne
    state: present
