---
# Create the admin-openrc.sh file which contains environment variables
# needed to authenticate as the admin user with the OpenStack CLI
- name: Create admin-openrc.sh file on controller
  ansible.builtin.template:
    src: admin-openrc.sh.j2
    dest: /root/admin-openrc.sh
    owner: root
    group: root
    mode: '0600'
  become: true
  when: inventory_hostname == 'controller'