---
# Install Keystone identity service, Apache2 web server, and WSGI module
# Also install python3-openstackclient for command-line management tools
- name: Install Keystone, Apache2, and WSGI module
  ansible.builtin.apt:
    name:
      - keystone
      - apache2
      - libapache2-mod-wsgi-py3
      - python3-openstackclient
    state: present
    update_cache: yes
  register: apt_result
  retries: 3
  delay: 5
  until: apt_result is success
  become: true
  notify: Restart apache2
  when: inventory_hostname == 'controller'