---
# Initialize the Keystone database by creating the database and user
- name: Initialize Keystone Database
  ansible.builtin.include_tasks: db_initialise.yml
  when: inventory_hostname == 'controller'

# Install Keystone identity service and Apache2 web server
- name: Install Keystone and Apache2
  ansible.builtin.include_tasks: keystone_compo.yml
  when: inventory_hostname == 'controller'

# Configure Keystone service with database connection and other settings
- name: Configure Keystone
  ansible.builtin.include_tasks: keystone_setup.yml
  when: inventory_hostname == 'controller'

# Configure Fernet and Credential key repositories for token and credential encryption
- name: Configure Fernet and Credential Repositories
  ansible.builtin.include_tasks: fernet_config.yml
  when: inventory_hostname == 'controller'

# Bootstrap the Keystone service to create initial admin user, project, and endpoints
- name: Bootstrap Keystone Service
  ansible.builtin.include_tasks: keystone_bootstrap.yml
  when: inventory_hostname == 'controller'

# Configure Apache web server for Keystone WSGI application
- name: Configure Apache
  ansible.builtin.include_tasks: apache2_conf.yml
  when: inventory_hostname == 'controller'

# Create the admin-openrc.sh file for CLI authentication
- name: Create OpenRC File
  ansible.builtin.include_tasks: create_openrc.yml
  when: inventory_hostname == 'controller'