---
- name: Install and Configure OpenStack Neutron
  hosts: controller
  become: yes
  vars:
    db_password: "neutron_db_pass"
    neutron_keystone_password: "neutron_pass"
    rabbitmq_user: "openstack"
    rabbitmq_password: "rabbit_pass"
    metadata_secret: "metadata_secret"
    overlay_interface_ip: "{{ ansible_default_ipv4.address }}"
    provider_interface: "{{ ansible_default_ipv4.interface }}"

  tasks:
    - name: Install Neutron packages
      apt:
        name:
          - neutron-server
          - neutron-plugin-ml2
          - neutron-linuxbridge-agent
          - neutron-l3-agent
          - neutron-dhcp-agent
          - neutron-metadata-agent
        state: present

    - name: Create Neutron database
      community.mysql.mysql_db:
        name: neutron
        state: present

    - name: Create Neutron database user
      community.mysql.mysql_user:
        name: neutron
        password: "{{ db_password }}"
        host: "%"
        priv: "neutron.*:ALL"
        state: present

    - name: Configure neutron.conf
      ini_file:
        path: /etc/neutron/neutron.conf
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        create: yes
      with_items:
        - { section: 'DEFAULT', option: 'core_plugin', value: 'ml2' }
        - { section: 'DEFAULT', option: 'service_plugins', value: 'router' }
        - { section: 'DEFAULT', option: 'allow_overlapping_ips', value: 'true' }
        - { section: 'DEFAULT', option: 'transport_url', value: 'rabbit://{{ rabbitmq_user }}:{{ rabbitmq_password }}@{{ inventory_hostname }}' }
        - { section: 'DEFAULT', option: 'auth_strategy', value: 'keystone' }
        - { section: 'database', option: 'connection', value: 'mysql+pymysql://neutron:{{ db_password }}@{{ inventory_hostname }}/neutron' }
        - { section: 'keystone_authtoken', option: 'www_authenticate_uri', value: 'http://{{ inventory_hostname }}:5000' }
        - { section: 'keystone_authtoken', option: 'auth_url', value: 'http://{{ inventory_hostname }}:5000' }
        - { section: 'keystone_authtoken', option: 'memcached_servers', value: '{{ inventory_hostname }}:11211' }
        - { section: 'keystone_authtoken', option: 'auth_type', value: 'password' }
        - { section: 'keystone_authtoken', option: 'project_domain_name', value: 'default' }
        - { section: 'keystone_authtoken', option: 'user_domain_name', value: 'default' }
        - { section: 'keystone_authtoken', option: 'project_name', value: 'service' }
        - { section: 'keystone_authtoken', option: 'username', value: 'neutron' }
        - { section: 'keystone_authtoken', option: 'password', value: '{{ neutron_keystone_password }}' }

    - name: Configure ML2 plugin
      ini_file:
        path: /etc/neutron/plugins/ml2/ml2_conf.ini
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { section: 'ml2', option: 'type_drivers', value: 'flat,vlan,vxlan' }
        - { section: 'ml2', option: 'tenant_network_types', value: 'vxlan' }
        - { section: 'ml2', option: 'mechanism_drivers', value: 'linuxbridge,l2population' }
        - { section: 'ml2', option: 'extension_drivers', value: 'port_security' }
        - { section: 'ml2_type_flat', option: 'flat_networks', value: 'provider' }
        - { section: 'ml2_type_vxlan', option: 'vni_ranges', value: '1:1000' }
        - { section: 'securitygroup', option: 'enable_ipset', value: 'true' }

    - name: Configure Linux Bridge agent
      ini_file:
        path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { section: 'linux_bridge', option: 'physical_interface_mappings', value: 'provider:{{ provider_interface }}' }
        - { section: 'vxlan', option: 'enable_vxlan', value: 'true' }
        - { section: 'vxlan', option: 'local_ip', value: '{{ overlay_interface_ip }}' }
        - { section: 'vxlan', option: 'l2_population', value: 'true' }
        - { section: 'securitygroup', option: 'enable_security_group', value: 'true' }
        - { section: 'securitygroup', option: 'firewall_driver', value: 'neutron.agent.linux.iptables_firewall.IptablesFirewallDriver' }

    - name: Configure L3 agent
      ini_file:
        path: /etc/neutron/l3_agent.ini
        section: 'DEFAULT'
        option: 'interface_driver'
        value: 'linuxbridge'

    - name: Configure DHCP agent
      ini_file:
        path: /etc/neutron/dhcp_agent.ini
        section: 'DEFAULT'
        option: 'interface_driver'
        value: 'linuxbridge'
      - ini_file:
          path: /etc/neutron/dhcp_agent.ini
          section: 'DEFAULT'
          option: 'enable_isolated_metadata'
          value: 'true'

    - name: Configure metadata agent
      ini_file:
        path: /etc/neutron/metadata_agent.ini
        section: 'DEFAULT'
        option: 'nova_metadata_host'
        value: '{{ inventory_hostname }}'
      - ini_file:
          path: /etc/neutron/metadata_agent.ini
          section: 'DEFAULT'
          option: 'metadata_proxy_shared_secret'
          value: '{{ metadata_secret }}'

    - name: Populate Neutron database
      command: >
        neutron-db-manage --config-file /etc/neutron/neutron.conf
        --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head

    - name: Restart and enable services
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - neutron-server
        - neutron-linuxbridge-agent
        - neutron-l3-agent
        - neutron-dhcp-agent
        - neutron-metadata-agent

    - name: Verify Neutron agents
      command: openstack network agent list
      register: agent_list
      changed_when: false
    - debug:
        var: agent_list.stdout_lines