- name: Install Nova compute packages
  ansible.builtin.apt:
    name:
      - nova-compute
      - libvirt-daemon-system
      - qemu-kvm
    state: present
    update_cache: yes

- name: Detect hardware virtualization
  command: egrep -c '(vmx|svm)' /proc/cpuinfo
  register: virt_result

- name: Set virt_type fact
  set_fact:
    virt_type: "{{ 'kvm' if virt_result.stdout|int > 0 else 'qemu' }}"

- name: Configure nova.conf
  ansible.builtin.template:
    src: nova.conf.j2
    dest: /etc/nova/nova.conf
    owner: root
    group: nova
    mode: '0640'

- name: Ensure libvirtd is enabled and started
  ansible.builtin.service:
    name: libvirtd
    state: started
    enabled: yes

- name: Ensure nova-compute is enabled and started
  ansible.builtin.service:
    name: nova-compute
    state: started
    enabled: yes 