---
<<<<<<< HEAD
- name: Install QEMU, KVM, and Libvirt on Ubuntu Server
=======
- name: Install QEMU, KVM, and Libvirt
>>>>>>> 889bfa9 (feat: add Ansible playbook to install KVM/Libvirt for VM host setup)
  hosts: kvm_hosts
  become: true
  tasks:
    - name: Install required packages
      apt:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - virtinst
          - virt-manager
        state: present
        update_cache: true

    - name: Ensure libvirtd service is running and enabled
      systemd:
        name: libvirtd
        enabled: true
        state: started

    - name: Add current user to libvirt and kvm groups
      user:
        name: "{{ ansible_user }}"
        groups: libvirt,kvm
        append: yes
