- name: Create Multipass instances
  hosts: localhost
  connection: local
  tasks:
    - name: Launch control node
      command: multipass launch --name ansible-vm1 --cpus 2 --mem 2G --disk 10G

    - name: Launch managed nodes
      command: multipass launch --name {{ item }} --cpus 1 --mem 1G --disk 5G
      loop:
        - node1
        - node2

- name: Configure Ansible control node
  hosts: ansible-vm1
  tasks:
    - name: Install Ansible
      apt:
        name: ansible
        state: present
        update_cache: yes

    - name: Ensure Python is installed
      apt:
        name: python3
        state: present
