- name: Install RabbitMQ server
  apt:
    name: rabbitmq-server
    state: present
  become: yes

- name: Ensure RabbitMQ is started and enabled
  service:
    name: rabbitmq-server
    state: started
    enabled: yes
  become: yes

- name: Add OpenStack RabbitMQ user
  rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    password: "{{ rabbitmq_password }}"
    state: present
    force: yes
  become: yes

- name: Set OpenStack RabbitMQ user tags
  rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    tags: administrator
    state: present
  become: yes

- name: Ensure OpenStack RabbitMQ user has permissions
  rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  become: yes