name: Documentation Review

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

<<<<<<< HEAD
<<<<<<< HEAD
      - name: Check commit message
        uses: ahmadnassri/action-commit-lint@v2

=======
>>>>>>> ee7ef50 (feat: doc-self check)
=======
      - name: Check commit message
        uses: ahmadnassri/action-commit-lint@v2

>>>>>>> 5392e6d (feat(ci): added commit-lint)
      - name: Vale linting
        uses: errata-ai/vale-action@v2
        with:
          files: '**/*.md'

      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: |
            docs/*.md
            *.md

      - name: Check for typos
        uses: sobolevn/misspell-fixer-action@master
        with:
<<<<<<< HEAD
          options: '-rsvn docs/'

      - name: Alex for inclusive language
<<<<<<< HEAD
        uses: theashraf/alex-action@master
=======
        uses: theashraf/alex-action@master
>>>>>>> ee7ef50 (feat: doc-self check)
=======
          options: '-rsvn docs/'      
>>>>>>> 5392e6d (feat(ci): added commit-lint)
