name: CI Test for OpenStack Keystone (Ansible only)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  keystone-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ansible, Python, etc.)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip ansible

      - name: Set executable permissions
        run: chmod +x ./ci-test.sh

      - name: Run CI test script (Ansible Playbooks)
        run: ./ci-test.sh

      - name: Upload logs if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ansible-logs
          path: playbooks/install_openstack/logs/
