name: Publish docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v5

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Install dependencies (MkDocs and Material theme)
      - name: Install dependencies
        run: |
          pip install mkdocs-material

      # Build and deploy the site to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/adorsys-gis/openstack.git

          mkdocs gh-deploy --force -m "chore: deploy documentation #{sha}" --dirty
