---
- name: Include common tasks
  include_role:
    name: common
    tasks_from: main

- name: Install compute packages
  package:
    name: "{{ 'neutron-linuxbridge-agent' if ansible_os_family == 'Debian' else 'openstack-neutron-linuxbridge' }}"
    state: present

- name: Configure Linux Bridge agent
  template:
    src: linuxbridge_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    owner: root
    group: neutron
    mode: "0640"
  notify: Restart neutron-linuxbridge-agent

# Trying to manually configure the nova component on the compute node 
- name: Updating apt package cache
  apt:
    update_cache: yes

- name: Install nova-compute
  apt:
    name: nova-compute
    state: present

- name: Configure nova-compute
  template:
    src: nova-compute.conf.j2
    dest: /etc/nova/nova.conf
    owner: root
    group: nova
    mode: 0640
  notify: Restart nova-compute


- name: Ensure nova-compute is started and enabled
  service:
    name: nova-compute
    state: started
    enabled: yes


- name: Configure Nova to use Neutron
  blockinfile:
    path: /etc/nova/nova.conf
    block: |
      [neutron]
      auth_url = {{ keystone_admin_url }}
      auth_type = password
      project_domain_name = default
      user_domain_name = default
      region_name = {{ region_name }}
      project_name = {{ openstack_service_project }}
      username = {{ neutron_keystone_user }}
      password = {{ neutron_keystone_password }}
      service_metadata_proxy = true
      metadata_proxy_shared_secret = {{ metadata_secret }}
    marker: "# {mark} ANSIBLE MANAGED: Neutron Configuration"
  notify: Restart nova-compute
