---
# OpenStack host configuration
openstack_host_ip: "{{ ansible_host | default(inventory_hostname) }}"
admin_password: "devstack"
database_password: "devstack"
rabbit_password: "devstack"
service_password: "devstack"

# Network configuration
fixed_range: "10.0.0.0/24"
floating_range: "172.24.4.0/24"
public_network_gateway: "172.24.4.225"
public_network_allocation_pool_start: "172.24.4.2"
public_network_allocation_pool_end: "172.24.4.254"
allocation_pools: "start={{ public_network_allocation_pool_start }},end={{ public_network_allocation_pool_end }}"
public_interface: "{{ neutron_public_interface }}"

# User configuration
stack_user: "stack"

# DevStack configuration
devstack_branch: "master"
devstack_repo: "https://github.com/openstack/devstack.git"

# System configuration
system_timezone: "UTC"
timezone: "{{ system_timezone }}"
log_dir: "/opt/stack/logs"

# Node roles
is_controller: "{{ inventory_hostname == 'node1' }}"
is_compute: "{{ inventory_hostname in ['node2', 'node3'] }}"

# Logging configuration
enable_logging: true

# Storage configuration
cinder_volume_size: "20G"
swift_hash_suffix: "66a3d6b56c1f479c8b4e70ab5c2000f5"
swift_replicas: 1

# Network configuration
neutron_use_security_groups: true
neutron_public_interface: "eth0"
neutron_private_interface: "eth1"
neutron_network_type: "flat"
neutron_physical_network: "public"

# OVN configuration
ovn_enable_tls: true
ovn_sb_port: 6642
ovn_nb_port: 6641
ovn_metadata_port: 9697
ovn_enable_chassis_as_gw: true
ovn_enable_tls_routing: true 
